version: '3.8'

services:
  fastapi:
    build:
      context: .
      dockerfile: api/Dockerfile
    container_name: fastapi_container
    ports:
      - "8080:8080"   
    env_file:
      - .env
    environment:
      - PORT=8080
      - REDIS_HOST=localhost
      - REDIS_PORT=6379
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: always

  streamlit:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: streamlit_container
    ports:
      - "8501:8501"  # Streamlit exposed on port 8501
    depends_on:
      - fastapi
    environment:
      - FASTAPI_URL=http://fastapi:8080
    restart: always
